### ISSUE TITLE
Add paid-for endpoints?

### ISSUE THREAD

**Issue by nilshg** [rando-brando/FinancialModelingPrep.jl#11]
Would you consider expanding the API to cover non-free bits of the service as well? And/or accept PRs to do so?

**Comment by rando-brando** [comment]
I would accept PRs for sure. I did include most paid endpoints but only for standard subscription which is what I can pay for as an individual. I wasn’t sure how to test the professional endpoints. I can just assume the same response format.

**Comment by nilshg** [comment]
I think that's reasonable - you could just note it's untested and let users report any issues.

**Comment by rando-brando** [comment]
Thanks a lot for your feedback! I can probably implement these changes quickly. Mind if I tag you as a PR reviewer when ready?

**Comment by nilshg** [comment]
Not at all.
