### ISSUE TITLE
More type conversions?

### ISSUE THREAD

**Issue by nilshg** [rando-brando/FinancialModelingPrep.jl#12]
Would you consider adding additional type conversions making the outputs easier to work with? 

E.g. `timestamp` results are currently integers so doing `Dates.unix2datetime(data.timestamp)` internally before returning the result might make things easier for users? Possibly to be disabled with a kwarg in case people want the "raw" outputs.

**Comment by rando-brando** [comment]
Interesting. I would definitely consider this. Can you point me to an example?

**Comment by nilshg** [comment]
Well basically what I said above, here are two random ones from `price_quote`, I haven't systematically looked through to see whether there are others that might make sense:

```
julia> pq = price_quote(fmp, "AAPL")
1-element Vector{Any}:
 Dict{String, Any}("avgVolume" => 73469776, "exchange" => "NASDAQ", "dayHigh" => 155.03, "price" => 154.67, "priceAvg200" => 147.2074, "changesPercentage" => 2.4101, "pe" => 26.26, "dayLow" => 153.46, "yearHigh" => 179.61, "sharesOutstanding" => 15821899776…)

julia> pq[1]["timestamp"]
1678115375

julia> using Dates

julia> Dates.unix2datetime(pq[1]["timestamp"])
2023-03-06T15:09:35

julia> pq[1]["earningsAnnouncement"]
"2023-04-26T10:59:00.000+0000"

julia> parse(DateTime, first(pq[1]["earningsAnnouncement"], 19))
2023-04-26T10:59:00
```

**Comment by nilshg** [comment]
I guess how you do this exactly depends partially on my other suggestion with `JSONTables`, as `JSON3` returned objects aren't mutable (not sure whether the tables created by `JSONTables` are).

**Comment by rando-brando** [comment]
Thank you so much for the feedback! I decided to do this project as a way to learn Julia so I'm still learning. I'll try it and let you know how it goes.

**Comment by rando-brando** [comment]
@nilshg It looks like `JSON3.read` converts vector-like responses to the `JSON3.Array` type which is exactly what `JSONTables.jsontable` requires. In the few cases the response is dictionary-like `JSON3.read` results in a `JSON3.Object` instead which does not work with `JSONTables.jsontable`. However, I cannot figure out how to convert this object into a `JSON3.Array`. Perhaps you know how? Instead I am reading those cases again with the argument `jsonlines = true`.

In regards to your immutable comment  it appears that you are correct. A `JSONTable.Table` contains `names`, `source` and `types` which refer to the column names, JSON3 source object, and the column types respectively. So in both states you cannot modify the immutable `JSON3.Array`.  The docs say to use `copy()` to make it mutable but this converts it to a standard `Vector` or `Dict` (same as `JSON.parse` did) which defeats the purpose of the `JSON3` + `JSONTables` approach. I do think your recommend solution is better but given I want the return to allow a flexible choice of data frame packages I don't see how I can easily modify the timestamp unless I try to modify its hex before parsing it.

``` julia
"""
    parse_json_response(response)

Parses a JSON response from the Financial Modeling Prep API server.

# Arguments
- response::HTTP.Messages.Response: An HTTP response containing JSON data.
"""
function parse_json_response(response::HTTP.Messages.Response)::JSONTables.Table
    result = JSON3.read(response.body)
    
    # raise error when the API response does
    if isa(result, JSON3.Object)
        if haskey(result, "Error Message")
            error(result["Error Message"])
        else
            # otherwise convert response to a json array
            result = JSON3.read(response.body, jsonlines = true)
        end
    end
    
    # convert result to a json table
    result = JSONTables.jsontable(result)

    return result
end

end # module Client
```

**Comment by rando-brando** [comment]
It may also be a good idea to break up the above function into 2 parts. For example when making a call to the historical endpoint you need to step into the JSON at `historical` in order to extract the table. This step in should be executed at the endpoint level.

``` julia
# convert result to a json table
result = result[1][:historical]
result = JSONTables.jsontable(result)
```

**Comment by nilshg** [comment]
Hm, I'll admit that I don't know much about the JSON ecosystem - I did know that JSONTables is backed by JSON3, and JSON3 is newer and faster than JSON although that comes at the cost of immutability. It's often useful to ask in #data on Slack for these kinds of design questions, there's a lot of very knowledgeable people there.

**Comment by nilshg** [comment]
One other related thing (couuld be a separate issue actually) is that with returning `Dict`s as is done currently the column order gets lost, which is annoying as e.g. the date and symbol columns end up somewhere random potentially towards the end of the table, making it hard to work out what data one is looking at.

**Comment by rando-brando** [comment]
Assuming using JSON3 fixes this then I think it’s the same issue. The issue being JSON package should be replaced with JSON3 + JSONTable functionality. To be clear the code I pasted above works. It’s just that in the rare case the response is Dict (no brackets) I’m reading it twice at the moment.

**Comment by rando-brando** [comment]
It looks like this issue was raised with JSON3 but is still an open issue. There may be no way to convert it directly.

https://github.com/quinnj/JSON3.jl/issues/234

**Comment by rando-brando** [comment]
@nilshg I'm currently moving forward with the below two-option parsing approach. In most cases the result can be parsed into a JSONTable via `parse_json_table`. In the few cases that it cannot I can use `parse_json_object` as a fallback.

``` julia
"""
    parse_json_object(response)
    parse_json_object(response, accessor)

Parses a response from the Financial Modeling Prep API server as a JSON object.

# Arguments
- response::HTTP.Messages.Response: An HTTP response containing JSON data.
- accessor: A Symbol or String accessor containing a nested array.
"""
function parse_json_object(response::HTTP.Messages.Response, accessor)::Union{JSON3.Object, JSON3.Array}
    result = JSON3.read(response.body)

    # raise error when the API response does
    if isa(result, JSON3.Object)
        if haskey(result, "Error Message")
            error(result["Error Message"])
        elseif haskey(result, accessor)
            result = result[accessor]
        end
    end

    return result
end
parse_json_object(response::HTTP.Messages.Response) = parse_json_object(response, nothing)

"""
    parse_json_table(response)
    parse_json_table(response, accessor)

    Parses a response from the Financial Modeling Prep API server as a JSON table.

# Arguments
- response::HTTP.Messages.Response: An HTTP response containing JSON data.
- accessor: A Symbol or String accessor containing a nested array.
"""
function parse_json_table(response::HTTP.Messages.Response, accessor)::JSONTables.Table
    result = parse_json_object(response, accessor)
    result = JSONTables.jsontable(result)
    return result
end
parse_json_table(response::HTTP.Messages.Response) = parse_json_table(response, nothing)
```
