### ISSUE TITLE
`price_quote` seems to query `Company-Quote` endpoint but docs don't mention this?

### ISSUE THREAD

**Issue by nilshg** [rando-brando/FinancialModelingPrep.jl#13]

**Comment by nilshg** [comment]
As the title says - afaict the `price_quote` function calls into

https://site.financialmodelingprep.com/developer/docs/#Company-Quote

but the docs only mention

> See [Stock-Quote](https://site.financialmodelingprep.com/developer/docs/#Stock-Price) for more details.
See [Index-Quote](https://site.financialmodelingprep.com/developer/docs/#Most-of-the-majors-indexes-(Dow-Jones%2C-Nasdaq%2C-S&P-500)) for more details.
See [Euronext-Quote](https://site.financialmodelingprep.com/developer/docs/#Most-of-the-EuroNext) for more details.
See [TSX-Quote](https://site.financialmodelingprep.com/developer/docs/#Most-of-the-TSX) for more details.
See [Crypto-Quote](https://site.financialmodelingprep.com/developer/docs/#Cryptocurrencies) for more details.
See [Forex-Quote](https://site.financialmodelingprep.com/developer/docs/#Forex-(FX)) for more details.
See [Commodity-Quote](https://site.financialmodelingprep.com/developer/docs/#Most-of-the-Major-Commodities-(Gold%2C-Silver%2C-Oil)) for more details

not `Company-Quote`? I might be misunderstanding something here...

**Comment by rando-brando** [comment]
I can change the first line to See [Company-Quote](https://site.financialmodelingprep.com/developer/docs/#Stock-Price) for more details. That should make it more clear.
